title: Jan Clarin
author: Jan Clarin
email: hi@janclarin.com
description: A little blog on the internet.
baseurl: ""
url: https://janclarin.com

date_format: "%m.%d.%y"

social_links:
  github: janclarin
  linkedin: janclarin
  twitter: janclarin

disqus_shortname: janclarin
google_analytics: UA-70490210-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
