title: Jan Clarin
author: Jan Clarin
email: hi@janclarin.com
description: >-
    A little blog about software development, productivity, and learning.
baseurl: ""
url: https://janclarin.com

social_links:
  github: janclarin
  linkedin: janclarin
  twitter: janclarin

disqus_shortname: janclarin
google_analytics: UA-70490210-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Not actually using this theme, just need to specify one for GitHub Pages.
theme: jekyll-theme-cayman
