title: Jan Clarin
author: Jan Clarin
email: hi@janclarin.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: https://janclarin.com

social_links:
  github: janclarin
  linkedin: janclarin
  twitter: janclarin

google_analytics: UA-70490210-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Not actually using this theme, just need to specify one for GitHub Pages.
theme: jekyll-theme-cayman
